# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/allen/memtest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/allen/memtest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/allen/memtest/CMakeFiles /home/allen/memtest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/allen/memtest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named memusr

# Build rule for target.
memusr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memusr
.PHONY : memusr

# fast build rule for target.
memusr/fast:
	$(MAKE) -f CMakeFiles/memusr.dir/build.make CMakeFiles/memusr.dir/build
.PHONY : memusr/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

memusr.o: memusr.cc.o

.PHONY : memusr.o

# target to build an object file
memusr.cc.o:
	$(MAKE) -f CMakeFiles/memusr.dir/build.make CMakeFiles/memusr.dir/memusr.cc.o
.PHONY : memusr.cc.o

memusr.i: memusr.cc.i

.PHONY : memusr.i

# target to preprocess a source file
memusr.cc.i:
	$(MAKE) -f CMakeFiles/memusr.dir/build.make CMakeFiles/memusr.dir/memusr.cc.i
.PHONY : memusr.cc.i

memusr.s: memusr.cc.s

.PHONY : memusr.s

# target to generate assembly for a file
memusr.cc.s:
	$(MAKE) -f CMakeFiles/memusr.dir/build.make CMakeFiles/memusr.dir/memusr.cc.s
.PHONY : memusr.cc.s

parser.o: parser.c.o

.PHONY : parser.o

# target to build an object file
parser.c.o:
	$(MAKE) -f CMakeFiles/memusr.dir/build.make CMakeFiles/memusr.dir/parser.c.o
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i

.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	$(MAKE) -f CMakeFiles/memusr.dir/build.make CMakeFiles/memusr.dir/parser.c.i
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s

.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	$(MAKE) -f CMakeFiles/memusr.dir/build.make CMakeFiles/memusr.dir/parser.c.s
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.c.s
.PHONY : parser.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... memusr"
	@echo "... rebuild_cache"
	@echo "... parser"
	@echo "... memusr.o"
	@echo "... memusr.i"
	@echo "... memusr.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

